# vals configuration for GCP Secret Manager
# Usage: vals env -f .vals.yaml
# Docs: https://github.com/helmfile/vals#gcp-secrets-manager

APP_SECRETS: ref+gcpsecrets://playground-447016/app-secrets
CRATES_TOKEN: ref+gcpsecrets://playground-447016/crates-token
DOCKER_PASSWORD: ref+gcpsecrets://playground-447016/docker-secret
GITHUB_TOKEN: ref+gcpsecrets://playground-447016/github-secret
MANAGER_SECRETS: ref+gcpsecrets://playground-447016/manager-secrets
