apiVersion: platform.yurikrupnik.com/v1alpha1
kind: Network
metadata:
  name: production-vpc
  namespace: default
  labels:
    cloud.provider/gcp: "true"
    environment: production
spec:
  parameters:
    region: us-central1
    cidrBlock: "10.0.0.0/16"
    enableDnsSupport: true
    enableDnsHostnames: true
    tags:
      environment: production
      team: platform
      cost-center: infrastructure
      managed-by: crossplane

    subnets:
      public:
        count: 3
        cidrMask: 24
      private:
        count: 3
        cidrMask: 24

    connectivity:
      natGateway:
        enabled: true
        highAvailability: false
      internetGateway:
        enabled: true

    security:
      defaultSecurityGroup:
        enabled: true
        allowInternalTraffic: true
        allowOutboundAll: true
      firewallRules:
        - name: allow-health-checks
          priority: 1000
          direction: ingress
          action: allow
          protocol: tcp
          ports: ["80", "443", "8080"]
          sourceCidrs:
            - "35.191.0.0/16"
            - "130.211.0.0/22"
        - name: allow-ssh-iap
          priority: 1001
          direction: ingress
          action: allow
          protocol: tcp
          ports: ["22"]
          sourceCidrs:
            - "35.235.240.0/20"

    observability:
      flowLogs:
        enabled: true
        trafficType: ALL

    clusterSecurity:
      privateClusterEndpoint: true
      podCidrBlock: "10.244.0.0/16"
      serviceCidrBlock: "10.96.0.0/12"
      networkPolicy: true

    gcp:
      project: my-production-project
      routingMode: REGIONAL
      privateGoogleAccess: true
      sharedVpc:
        enabled: false
