// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloud provider enumeration
 */
export type CloudProvider = "aws" | "azure" | "gcp";
