// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudProvider } from "./CloudProvider";
import type { Money } from "./Money";
import type { PricingUnit } from "./PricingUnit";
import type { ResourceType } from "./ResourceType";

/**
 * DTO for creating a new price entry
 */
export type CreatePriceEntry = { provider: CloudProvider, resource_type: ResourceType, sku: string, service_name: string, product_family: string, instance_type: string | null, region: string, unit_price: Money, pricing_unit: PricingUnit, description: string, attributes: { [key in string]?: string }, effective_date: string, expiration_date: string | null, };
