// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pricing unit enumeration
 */
export type PricingUnit = "hour" | "month" | "gb" | "gbhour" | "gbmonth" | "request" | "millionrequests" | "second" | "unit";
