// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";
import type { ProviderPrice } from "./ProviderPrice";

/**
 * Price comparison result
 */
export type PriceComparison = { 
/**
 * Comparison key (e.g., "4vcpu-8gb-compute")
 */
comparison_key: string, 
/**
 * Prices from each provider
 */
provider_prices: Array<ProviderPrice>, 
/**
 * Cheapest option
 */
cheapest: ProviderPrice | null, 
/**
 * Potential savings vs. most expensive
 */
potential_savings: Money | null, };
