// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudProvider } from "./CloudProvider";
import type { Money } from "./Money";
import type { PricingUnit } from "./PricingUnit";
import type { ResourceType } from "./ResourceType";

/**
 * Price entry representing a single pricing record
 */
export type PriceEntry = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Cloud provider
 */
provider: CloudProvider, 
/**
 * Resource type
 */
resource_type: ResourceType, 
/**
 * Provider-specific SKU
 */
sku: string, 
/**
 * Service name (e.g., "Amazon EC2", "Azure VMs")
 */
service_name: string, 
/**
 * Product family (e.g., "Compute Instance")
 */
product_family: string, 
/**
 * Instance type (e.g., "t3.medium", "Standard_D2s_v3")
 */
instance_type: string | null, 
/**
 * Region code
 */
region: string, 
/**
 * Unit price
 */
unit_price: Money, 
/**
 * Pricing unit
 */
pricing_unit: PricingUnit, 
/**
 * Description
 */
description: string, 
/**
 * Additional attributes (vCPU, memory, etc.)
 */
attributes: { [key in string]?: string }, 
/**
 * When this price became effective
 */
effective_date: string, 
/**
 * When this price expires (null if current)
 */
expiration_date: string | null, 
/**
 * When we fetched this price
 */
collected_at: string, 
/**
 * Creation timestamp
 */
created_at: string, 
/**
 * Last update timestamp
 */
updated_at: string, };
