// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudProvider } from "./CloudProvider";
import type { Money } from "./Money";
import type { PriceEntry } from "./PriceEntry";

/**
 * Provider price for comparison
 */
export type ProviderPrice = { provider: CloudProvider, price: PriceEntry, 
/**
 * Estimated monthly cost
 */
monthly_estimate: Money, };
