// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource type enumeration
 */
export type ResourceType = "compute" | "storage" | "database" | "network" | "serverless" | "analytics" | "kubernetes" | "other";
