// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

/**
 * DTO for updating an existing price entry
 */
export type UpdatePriceEntry = { unit_price: Money | null, description: string | null, attributes: { [key in string]?: string } | null, expiration_date: string | null, };
