// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file apps/v1/common.proto (package commons, syntax proto3)
/* eslint-disable */

import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2';

/**
 * Describes the file apps/v1/common.proto.
 */
export const file_apps_v1_common: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChRhcHBzL3YxL2NvbW1vbi5wcm90bxIHY29tbW9ucyIQCgJJZBIKCgJpZBgBIAEoCSIUCgROYW1lEgwKBG5hbWUYASABKAkiWAoFUXVlcnkSEgoKYXR0cmlidXRlcxgBIAMoCRINCgV3aGVyZRgCIAEoCRINCgVvcmRlchgDIAEoCRIOCgZvZmZzZXQYBCABKAUSDQoFbGltaXQYBSABKAUiFgoFQ291bnQSDQoFY291bnQYASABKAVCZAoLY29tLmNvbW1vbnNCC0NvbW1vblByb3RvUAFaDGdycGMvY29tbW9uc6ICA0NYWKoCB0NvbW1vbnPKAgdDb21tb25z4gITQ29tbW9uc1xHUEJNZXRhZGF0YeoCB0NvbW1vbnNiBnByb3RvMw',
  );

/**
 * @generated from message commons.Id
 */
export type Id = Message<'commons.Id'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message commons.Id.
 * Use `create(IdSchema)` to create a new message.
 */
export const IdSchema: GenMessage<Id> =
  /*@__PURE__*/
  messageDesc(file_apps_v1_common, 0);

/**
 * @generated from message commons.Name
 */
export type Name = Message<'commons.Name'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message commons.Name.
 * Use `create(NameSchema)` to create a new message.
 */
export const NameSchema: GenMessage<Name> =
  /*@__PURE__*/
  messageDesc(file_apps_v1_common, 1);

/**
 * @generated from message commons.Query
 */
export type Query = Message<'commons.Query'> & {
  /**
   * @generated from field: repeated string attributes = 1;
   */
  attributes: string[];

  /**
   * @generated from field: string where = 2;
   */
  where: string;

  /**
   * @generated from field: string order = 3;
   */
  order: string;

  /**
   * @generated from field: int32 offset = 4;
   */
  offset: number;

  /**
   * @generated from field: int32 limit = 5;
   */
  limit: number;
};

/**
 * Describes the message commons.Query.
 * Use `create(QuerySchema)` to create a new message.
 */
export const QuerySchema: GenMessage<Query> =
  /*@__PURE__*/
  messageDesc(file_apps_v1_common, 2);

/**
 * @generated from message commons.Count
 */
export type Count = Message<'commons.Count'> & {
  /**
   * @generated from field: int32 count = 1;
   */
  count: number;
};

/**
 * Describes the message commons.Count.
 * Use `create(CountSchema)` to create a new message.
 */
export const CountSchema: GenMessage<Count> =
  /*@__PURE__*/
  messageDesc(file_apps_v1_common, 3);
