// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file apps/v1/common.proto (package commons.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/v1/common.proto.
 */
export const file_apps_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChRhcHBzL3YxL2NvbW1vbi5wcm90bxIKY29tbW9ucy52MSIQCgJJZBIKCgJpZBgBIAEoCSIUCgROYW1lEgwKBG5hbWUYASABKAkiWAoFUXVlcnkSEgoKYXR0cmlidXRlcxgBIAMoCRINCgV3aGVyZRgCIAEoCRINCgVvcmRlchgDIAEoCRIOCgZvZmZzZXQYBCABKAUSDQoFbGltaXQYBSABKAUiFgoFQ291bnQSDQoFY291bnQYASABKAVCdwoOY29tLmNvbW1vbnMudjFCC0NvbW1vblByb3RvUAFaD2dycGMvY29tbW9ucy92MaICA0NYWKoCCkNvbW1vbnMuVjHKAgpDb21tb25zXFYx4gIWQ29tbW9uc1xWMVxHUEJNZXRhZGF0YeoCC0NvbW1vbnM6OlYxYgZwcm90bzM");

/**
 * @generated from message commons.v1.Id
 */
export type Id = Message<"commons.v1.Id"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message commons.v1.Id.
 * Use `create(IdSchema)` to create a new message.
 */
export const IdSchema: GenMessage<Id> = /*@__PURE__*/
  messageDesc(file_apps_v1_common, 0);

/**
 * @generated from message commons.v1.Name
 */
export type Name = Message<"commons.v1.Name"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message commons.v1.Name.
 * Use `create(NameSchema)` to create a new message.
 */
export const NameSchema: GenMessage<Name> = /*@__PURE__*/
  messageDesc(file_apps_v1_common, 1);

/**
 * @generated from message commons.v1.Query
 */
export type Query = Message<"commons.v1.Query"> & {
  /**
   * @generated from field: repeated string attributes = 1;
   */
  attributes: string[];

  /**
   * @generated from field: string where = 2;
   */
  where: string;

  /**
   * @generated from field: string order = 3;
   */
  order: string;

  /**
   * @generated from field: int32 offset = 4;
   */
  offset: number;

  /**
   * @generated from field: int32 limit = 5;
   */
  limit: number;
};

/**
 * Describes the message commons.v1.Query.
 * Use `create(QuerySchema)` to create a new message.
 */
export const QuerySchema: GenMessage<Query> = /*@__PURE__*/
  messageDesc(file_apps_v1_common, 2);

/**
 * @generated from message commons.v1.Count
 */
export type Count = Message<"commons.v1.Count"> & {
  /**
   * @generated from field: int32 count = 1;
   */
  count: number;
};

/**
 * Describes the message commons.v1.Count.
 * Use `create(CountSchema)` to create a new message.
 */
export const CountSchema: GenMessage<Count> = /*@__PURE__*/
  messageDesc(file_apps_v1_common, 3);

