k8s_yaml(kustomize('k8s/kustomize/overlays/dev'))

k8s_resource(
    objects=['zerg-shared-config:configmap', 'zerg-shared-secrets:secret'],
    new_name='zerg-shared-config',
    labels=['config'],
)
