apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: scheduled-tasks
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 5m"
    - name: direction
      value: input
scopes:
  - zerg-tasks
