apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nats-pubsub
  namespace: default
spec:
  type: pubsub.nats-jetstream
  version: v1
  metadata:
    - name: natsURL
      value: "nats://localhost:4222"
    - name: name
      value: "tasks-stream"
    - name: durableName
      value: "tasks-consumer"
    - name: queueGroupName
      value: "task-workers"
    - name: startSequence
      value: "1"
    - name: flowControl
      value: "false"
    - name: ackWait
      value: "30s"
    - name: maxDeliver
      value: "5"
    - name: backOff
      value: "1s,5s,10s"
    - name: maxAckPending
      value: "1000"
    - name: replicas
      value: "1"
    - name: memoryStorage
      value: "false"
scopes:
  - zerg-api
  - zerg-nats-worker
