apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-mongodb
  namespace: default
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: "localhost:27017"
    - name: databaseName
      value: "nx_playground"
    - name: collectionName
      value: "dapr_state"
    - name: writeConcern
      value: "majority"
    - name: readConcern
      value: "majority"
    - name: operationTimeout
      value: "10s"
scopes:
  - products-api
