apiVersion: platform.yurikrupnik.com/v1alpha1
kind: ContainerRegistry
metadata:
  name: production-ecr
  namespace: default
  labels:
    cloud.provider/aws: "true"
    environment: production
spec:
  parameters:
    region: us-east-1
    repositoryName: production-app
    imageTagMutability: IMMUTABLE
    tags:
      Environment: production
      Team: platform
      CostCenter: infrastructure
      ManagedBy: crossplane

    security:
      scanOnPush: true
      encryptionType: KMS
      kmsKeyId: "arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012"
      publicAccess: false

    lifecycle:
      enabled: true
      maxImageAge: 90
      maxImageCount: 1000
      keepTagPatterns:
        - "latest"
        - "v*"
        - "release-*"
        - "main-*"

    replication:
      enabled: true
      destinationRegions:
        - us-west-2
        - eu-west-1
        - ap-southeast-1

    accessControl:
      pullPrincipals:
        - "arn:aws:iam::123456789012:role/EKSProdNodeRole"
        - "arn:aws:iam::123456789012:role/LambdaExecutionRole"
      pushPrincipals:
        - "arn:aws:iam::123456789012:role/GitHubActionsCICD"
        - "arn:aws:iam::123456789012:role/JenkinsCICD"

    aws:
      forceDelete: false
      scanType: ENHANCED
      pullThroughCache:
        enabled: true
        upstreamRegistries:
          - prefix: "ecr-public"
            upstream: "public.ecr.aws"
          - prefix: "docker-hub"
            upstream: "docker.io"
          - prefix: "quay"
            upstream: "quay.io"
          - prefix: "ghcr"
            upstream: "ghcr.io"
