// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatContext } from "./ChatContext";
import type { SessionStatus } from "./SessionStatus";

/**
 * Chat session for conversation persistence
 */
export type ChatSession = { id: string, user_id: string | null, title: string | null, context: ChatContext, status: SessionStatus, created_at: string, updated_at: string, };
