// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallRecord } from "./ToolCallRecord";

/**
 * Chat response
 */
export type ChatResponse = { session_id: string, content: string, tool_calls: Array<ToolCallRecord>, };
