// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudProvider } from "./CloudProvider";

/**
 * Chat context for session preferences
 */
export type ChatContext = { 
/**
 * Preferred cloud providers
 */
preferred_providers: Array<CloudProvider>, 
/**
 * Monthly budget constraint (in cents)
 */
budget_monthly: bigint | null, 
/**
 * Preferred regions
 */
regions: Array<string>, 
/**
 * Compliance requirements (e.g., "hipaa", "pci-dss")
 */
compliance_requirements: Array<string>, 
/**
 * Connected cloud account IDs for this session
 */
cloud_account_ids: Array<string>, };
