// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageRole } from "./MessageRole";
import type { ToolCallRecord } from "./ToolCallRecord";

/**
 * Chat message with tool calls
 */
export type ChatMessage = { id: string, session_id: string, role: MessageRole, content: string | null, tool_calls: Array<ToolCallRecord> | null, token_count: number | null, latency_ms: number | null, created_at: string, };
