// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceSpecs } from "./ResourceSpecs";
import type { Utilization } from "./Utilization";

/**
 * Cached cloud resource inventory
 */
export type CloudResource = { id: string, account_id: string, resource_id: string, resource_type: string, region: string, name: string | null, specs: ResourceSpecs, monthly_cost_cents: bigint | null, utilization: Utilization | null, last_seen_at: string, created_at: string, };
