// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudAccountStatus } from "./CloudAccountStatus";
import type { CloudProvider } from "./CloudProvider";

/**
 * Connected cloud account for resource exploration
 */
export type CloudAccount = { id: string, user_id: string, provider: CloudProvider, account_id: string, name: string | null, regions: Array<string>, last_sync_at: string | null, status: CloudAccountStatus, created_at: string, };
