// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cloud account connection status
 */
export type CloudAccountStatus = "pending" | "connected" | "error" | "disconnected";
