// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";

/**
 * Money representation with precision
 */
export type Money = { 
/**
 * Amount in the smallest currency unit (cents for USD)
 */
amount: bigint, 
/**
 * Currency type
 */
currency: Currency, 
/**
 * Number of decimal places (2 for cents)
 */
decimal_places: number, };
