// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";
import type { Recommendation } from "./Recommendation";

/**
 * Optimization summary
 */
export type OptimizationSummary = { total_recommendations: bigint, total_monthly_savings: Money, total_annual_savings: Money, by_type: { [key in string]?: bigint }, top_recommendations: Array<Recommendation>, };
