// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecommendationDetails } from "./RecommendationDetails";
import type { RecommendationStatus } from "./RecommendationStatus";
import type { RecommendationType } from "./RecommendationType";

/**
 * Optimization recommendation
 */
export type Recommendation = { id: string, session_id: string | null, resource_id: string | null, recommendation_type: RecommendationType, title: string, description: string, current_cost_cents: bigint | null, projected_cost_cents: bigint | null, savings_cents: bigint | null, confidence: number | null, details: RecommendationDetails | null, status: RecommendationStatus, created_at: string, };
