// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recommendation status
 */
export type RecommendationStatus = "pending" | "approved" | "applied" | "dismissed" | "failed";
