// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recommendation type
 */
export type RecommendationType = "rightsize" | "terminate" | "migrate" | "reserve" | "upgrade" | "consolidate";
