// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudProvider } from "./CloudProvider";

/**
 * Recommendation details
 */
export type RecommendationDetails = { risks: Array<string>, implementation_steps: Array<string>, estimated_downtime: string | null, target_provider: CloudProvider | null, target_region: string | null, target_instance_type: string | null, };
