// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";
import type { RegionSummary } from "./RegionSummary";
import type { TypeSummary } from "./TypeSummary";

/**
 * Resource summary for aggregation
 */
export type ResourceSummary = { total_count: bigint, total_monthly_cost: Money, by_type: { [key in string]?: TypeSummary }, by_region: { [key in string]?: RegionSummary }, };
