// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource specifications
 */
export type ResourceSpecs = { instance_type: string | null, vcpus: number | null, memory_gb: number | null, storage_gb: number | null, state: string | null, };
