// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool call record
 */
export type ToolCallRecord = { name: string, arguments: string, result: string | null, latency_ms: bigint | null, };
