// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Money } from "./Money";

/**
 * Type summary
 */
export type TypeSummary = { count: bigint, monthly_cost: Money, };
