// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource utilization metrics
 */
export type Utilization = { cpu_avg: number | null, memory_avg: number | null, network_in_bytes: bigint | null, network_out_bytes: bigint | null, storage_used_bytes: bigint | null, };
