apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.database.platform.io
spec:
  group: database.platform.io
  names:
    kind: XDatabase
    plural: xdatabases
  claimNames:
    kind: Database
    plural: databases
  defaultCompositionRef:
    name: xdatabase
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - provider
            - engine
            properties:
              provider:
                type: string
                description: Cloud provider (aws, gcp) or kubernetes for CloudNative-PG
                enum:
                - aws
                - gcp
                - kubernetes
              region:
                type: string
                description: Cloud region (required for aws/gcp, ignored for kubernetes)
              engine:
                type: string
                description: Database engine (kubernetes only supports postgres)
                enum:
                - postgres
                - mysql
                default: postgres
              engineVersion:
                type: string
                description: Database engine version
                default: '15'
              size:
                type: string
                description: Instance size
                enum:
                - small
                - medium
                - large
                default: small
              storageGB:
                type: integer
                description: Storage size in GB
                default: 20
              instances:
                type: integer
                description: Number of instances (kubernetes/CNPG only)
                default: 1
              namespace:
                type: string
                description: Target namespace for kubernetes provider
                default: default
              environment:
                type: string
                description: Environment (dev, staging, prod)
                enum:
                - dev
                - staging
                - prod
                default: dev
              deletionPolicy:
                type: string
                description: Deletion policy
                enum:
                - Delete
                - Orphan
                default: Delete
          status:
            type: object
            properties:
              provider:
                type: string
              region:
                type: string
              engine:
                type: string
              endpoint:
                type: string
    additionalPrinterColumns: null
