apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.database.platform.io
spec:
  group: database.platform.io
  names:
    kind: XDatabase
    plural: xdatabases
  claimNames:
    kind: Database
    plural: databases
  defaultCompositionRef:
    name: xdatabase
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - provider
            - engine
            properties:
              provider:
                type: string
                description: Cloud provider (aws, gcp) or kubernetes for CloudNative-PG
                enum:
                - aws
                - gcp
                - kubernetes
              region:
                type: string
                description: Cloud region (required for aws/gcp, ignored for kubernetes)
              engine:
                type: string
                description: Database engine (kubernetes only supports postgres)
                enum:
                - postgres
                - mysql
                default: postgres
              engineVersion:
                type: string
                description: Database engine version
                default: '18'
              size:
                type: string
                description: Instance size
                enum:
                - small
                - medium
                - large
                - xlarge
                default: small
              storageGB:
                type: integer
                description: Storage size in GB (20-65536)
                default: 20
              storageType:
                type: string
                description: 'Storage type (AWS: gp2, gp3, io1; GCP: SSD)'
                default: gp3
              multiAZ:
                type: boolean
                description: Enable Multi-AZ (AWS) or Regional availability (GCP)
                default: false
              publiclyAccessible:
                type: boolean
                description: Allow public access (not recommended)
                default: false
              instances:
                type: integer
                description: Number of instances (kubernetes/CNPG only)
                default: 1
              namespace:
                type: string
                description: Target namespace for kubernetes provider
                default: default
              environment:
                type: string
                description: Environment (dev, staging, prod)
                enum:
                - dev
                - staging
                - prod
                default: dev
              deletionPolicy:
                type: string
                description: Deletion policy
                enum:
                - Delete
                - Orphan
                default: Delete
              tags:
                type: object
                description: Custom tags/labels to apply to resources
                additionalProperties:
                  type: string
              backup:
                type: object
                description: Backup configuration
                properties:
                  enabled:
                    type: boolean
                    default: true
                    description: Enable automated backups
                  retentionDays:
                    type: integer
                    default: 7
                    minimum: 0
                    maximum: 35
                    description: Number of days to retain backups
                  preferredWindow:
                    type: string
                    default: '03:00-04:00'
                    description: Preferred backup window (UTC)
              secrets:
                type: object
                description: Secrets configuration for credentials
                properties:
                  generatePassword:
                    type: boolean
                    default: true
                    description: Auto-generate database password
                  passwordSecretRef:
                    type: string
                    description: Reference to existing password secret
                  usernameSecretRef:
                    type: string
                    description: Reference to existing username secret
          status:
            type: object
            properties:
              provider:
                type: string
              region:
                type: string
              engine:
                type: string
              endpoint:
                type: string
    additionalPrinterColumns: null
